- name: loops
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: print packages
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    loop:
    - git
    - mysql
    - postfix
