192.168.23.30
192.168.23.32

[web]
54.160.183.13

[cart]
192.168.23.32
192.161.26.31

[catalogue]
199.164.29.31
191.121.21.32

[roboshop:children]
web
cart
catalogue

[localhost]
localhost

[localhost:vars]
Course="DevOps From inventory"
Trainer="Sivakumar"
Duration="110HRS"
PERSON="Siva from inventory"
WISHES="Morning from inventory"